// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMwXTIzLNYhX5AiTFHY7kV2Ige2mvF2_8',
    appId: '1:309438403428:web:67af81a5b32745928f6071',
    messagingSenderId: '309438403428',
    projectId: 'raqame-e8e8c',
    authDomain: 'raqame-e8e8c.firebaseapp.com',
    storageBucket: 'raqame-e8e8c.appspot.com',
    measurementId: 'G-JSJYXEZYVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWIFpaNurCcQhWNMDl50zPNWmQGJk8rbc',
    appId: '1:309438403428:android:6bfe10e958750d838f6071',
    messagingSenderId: '309438403428',
    projectId: 'raqame-e8e8c',
    storageBucket: 'raqame-e8e8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS1Q8IrM5zDtRsRHDGBh4hzVMhdq68i_4',
    appId: '1:309438403428:ios:6fb9cd551c3e04138f6071',
    messagingSenderId: '309438403428',
    projectId: 'raqame-e8e8c',
    storageBucket: 'raqame-e8e8c.appspot.com',
    iosClientId: '309438403428-4q1su3qhg2tfph7srau9av7dkabrgohm.apps.googleusercontent.com',
    iosBundleId: 'com.eamana.raqame',
  );
}
